package com.example.ui

object LanguageHelper {
    private val translations = mapOf(
        "en" to mapOf(
            "app_title" to "Smarters IPTV",
            "live_tv" to "Live TV",
            "movies" to "Movies",
            "series" to "Series",
            "favorites" to "Favorites",
            "parental" to "Parental Controls",
            "settings" to "Settings",
            "add_playlist" to "Add Playlist",
            "m3u_tab" to "M3U Link",
            "xtream_tab" to "Xtream Codes",
            "playlist_name" to "Playlist Name",
            "server_url" to "Server URL",
            "username" to "Username",
            "password" to "Password",
            "m3u_url" to "M3U Playlist URL",
            "load_demo" to "Demo Provider / Sample Portal",
            "demo_desc" to "Immediately load high-performance demo channels & open-source VOD movies",
            "connect" to "Connect Playlist",
            "authenticating" to "Authenticating...",
            "no_playlists" to "No IPTV Playlists Configured",
            "no_playlists_desc" to "Please load our public demo provider or add your custom Xtream/M3U subscription detailing.",
            "search_hint" to "Search channel or title...",
            "current_show" to "Current Program Guide",
            "no_epg" to "No EPG Guide Info Scheduled",
            "player_core" to "Video Player Engine",
            "parental_desc" to "Lock and hide adult categories or restrict sensitive streaming nodes.",
            "enter_pin" to "Enter Parental PIN",
            "set_pin" to "Configure Parental PIN",
            "pin_incorrect" to "PIN Incorrect! Access Denied.",
            "pin_set_success" to "Parental PIN code applied successfully.",
            "lock_activated" to "Parental lock successfully applied.",
            "lock_disabled" to "Parental locks deactivated.",
            "save_changes" to "Save Configs",
            "epg_timeline" to "Electronic Program Timeline (EPG)",
            "play_hd" to "HD Dynamic Stream (Auto)",
            "switch_core" to "Active Player Core",
            "active_playlist" to "Active Provider",
            "change_lang" to "Application Language",
            "favorites_empty" to "No favorite streams bookmarked yet.",
            "cloud_sync_title" to "Cloud Sync Portal",
            "cloud_sync_desc" to "Synchronize and remotely provision your IPTV subscription parameters securely.",
            "email_label" to "Email Address",
            "password_label" to "Password",
            "sign_in_btn" to "SIGN IN",
            "sign_up_btn" to "SIGN UP",
            "google_signin" to "Sync with Google",
            "facebook_signin" to "Sync with Facebook",
            "or_label" to "OR SYNCHRONIZE WITH",
            "skip_label" to "Skip and Use Local Input",
            "provision_title" to "Provision New Portal",
            "host_url" to "Host URL / Domain",
            "port_label" to "Port",
            "provision_btn" to "Add Provisioned Stream",
            "active_provision" to "Your Cloud Portals",
            "logout_btn" to "Disconnect Cloud Sync"
        ),
        "es" to mapOf(
            "app_title" to "Smarters IPTV",
            "live_tv" to "TV en Vivo",
            "movies" to "Películas",
            "series" to "Series TV",
            "favorites" to "Favoritos",
            "parental" to "Control Parental",
            "settings" to "Ajustes",
            "add_playlist" to "Añadir Lista de Reproducción",
            "m3u_tab" to "Enlace M3U",
            "xtream_tab" to "Xtream Codes",
            "playlist_name" to "Nombre de la Lista",
            "server_url" to "URL del Servidor",
            "username" to "Usuario",
            "password" to "Contraseña",
            "m3u_url" to "Enlace de M3U Playlist",
            "load_demo" to "Proveedor de Demostración",
            "demo_desc" to "Carga canales de demostración legales y películas abiertas al instante",
            "connect" to "Conectar Lista",
            "authenticating" to "Autenticando...",
            "no_playlists" to "No hay listas IPTV configuradas",
            "no_playlists_desc" to "Cargue el proveedor de demostración público o añada su suscripción M3U/Xtream.",
            "search_hint" to "Buscar canal o película...",
            "current_show" to "Guía de Programa Actual",
            "no_epg" to "Guía de Programación No Disponible",
            "player_core" to "Motor de Reproductor",
            "parental_desc" to "Bloquee categorías adultas o restrinja transmisiones sensibles.",
            "enter_pin" to "Introducir PIN Parental",
            "set_pin" to "Configurar PIN Parental",
            "pin_incorrect" to "¡PIN Incorrecto! Acceso Denegado.",
            "pin_set_success" to "Código PIN configurado correctamente.",
            "lock_activated" to "Bloqueo parental activado.",
            "lock_disabled" to "Sistemas de bloqueo desactivados.",
            "save_changes" to "Guardar Ajustes",
            "epg_timeline" to "Guía Electrónica de Canales",
            "play_hd" to "Transmisión HD Dinámica",
            "switch_core" to "Núcleo de Reproductor",
            "active_playlist" to "Proveedor Activo",
            "change_lang" to "Idioma de la Aplicación",
            "favorites_empty" to "Aún no ha marcado transmisiones favoritas."
        ),
        "fr" to mapOf(
            "app_title" to "Smarters IPTV",
            "live_tv" to "TV en Direct",
            "movies" to "Films VOD",
            "series" to "Séries TV",
            "favorites" to "Favoris",
            "parental" to "Contrôle Parental",
            "settings" to "Paramètres",
            "add_playlist" to "Ajouter un Abonnement",
            "m3u_tab" to "Lien M3U",
            "xtream_tab" to "Codes Xtream",
            "playlist_name" to "Nom de l'abonnement",
            "server_url" to "URL du Serveur",
            "username" to "Nom d'utilisateur",
            "password" to "Mot de passe",
            "m3u_url" to "Lien URL de la liste M3U",
            "load_demo" to "Fournisseur Démo Gratuit",
            "demo_desc" to "Chargez instantanément des chaînes de télévision légales ouvertes",
            "connect" to "Se Connecter",
            "authenticating" to "Authentification...",
            "no_playlists" to "Aucun abonnement paramétré",
            "no_playlists_desc" to "Veuillez charger notre démo ou renseigner vos informations d'abonnement.",
            "search_hint" to "Rechercher une chaîne, un film...",
            "current_show" to "Programme TV en cours",
            "no_epg" to "Aucun guide des programmes",
            "player_core" to "Moteur Graphique",
            "parental_desc" to "Masquer et verrouiller l'accès aux flux de catégorie adulte.",
            "enter_pin" to "Entrer le code PIN",
            "set_pin" to "Créer un code PIN",
            "pin_incorrect" to "Code PIN Incorrect! Accès refusé.",
            "pin_set_success" to "Code PIN enregistré avec succès.",
            "lock_activated" to "Contrôle parental activé.",
            "lock_disabled" to "Contrôle parental désactivé.",
            "save_changes" to "Sauvegarder",
            "epg_timeline" to "Grille des Programmes TV",
            "play_hd" to "Flux Haute Définition (HD)",
            "switch_core" to "Lecteur Vidéo Actif",
            "active_playlist" to "Abonnement Actif",
            "change_lang" to "Langue de l'application",
            "favorites_empty" to "Aucun favori enregistré pour le moment."
        ),
        "ar" to mapOf(
            "app_title" to "Smarters IPTV",
            "live_tv" to "بث تلفزيوني مباشر",
            "movies" to "أفلام",
            "series" to "مسلسلات",
            "favorites" to "المفضلة",
            "parental" to "الرقابة الأبوية",
            "settings" to "الإعدادات",
            "add_playlist" to "إضافة قائمة قنوات",
            "m3u_tab" to "رابط M3U",
            "xtream_tab" to "أكواد Xtream",
            "playlist_name" to "اسم القائمة",
            "server_url" to "عنوان السيرفر",
            "username" to "اسم المستخدم",
            "password" to "كلمة المرور",
            "m3u_url" to "رابط قائمة M3U",
            "load_demo" to "تجرية البث التجريبي",
            "demo_desc" to "تحميل القنوات التجريبية المجانية والأفلام المفتوحة فوراً",
            "connect" to "اتصال",
            "authenticating" to "جاري التحقق...",
            "no_playlists" to "لا توجد قوائم تشغيل مضافة",
            "no_playlists_desc" to "يرجى إضافة قائمة يدويًا أو الاستمتاع بالبث التجريبي العام المعتمد.",
            "search_hint" to "بحث عن قناة أو فيلم...",
            "current_show" to "دليل البرنامج الحالي",
            "no_epg" to "لا يوجد جدول بث حالي",
            "player_core" to "محرك تشغيل الفيديو",
            "parental_desc" to "إغلاق وتعمية القنوات الحساسة برمز أمان مخصص.",
            "enter_pin" to "أدخل الرمز الأبوي",
            "set_pin" to "ضبط الرمز الأبوي",
            "pin_incorrect" to "الرمز خاطئ! تم رفض الدخول.",
            "pin_set_success" to "تم تعيين رمز الأمان بنجاح.",
            "lock_activated" to "تم تفعيل القفل الأبوي بنجاح.",
            "lock_disabled" to "تم إلغاء تفعيل القفل الأبوي.",
            "save_changes" to "حفظ التغييرات",
            "epg_timeline" to "جدول البرامج الإلكتروني",
            "play_hd" to "تشغيل بجودة عالية HD",
            "switch_core" to "محرك التشغيل المفعل",
            "active_playlist" to "القائمة النشطة",
            "change_lang" to "لغة التطبيق",
            "favorites_empty" to "لم تقم بإضافة أي قناة للمفضلة حتى الآن."
        ),
        "hi" to mapOf(
            "app_title" to "Smarters IPTV",
            "live_tv" to "लाइव टीवी",
            "movies" to "फ़िल्में",
            "series" to "टीवी श्रृंखला",
            "favorites" to "पसंदीदा",
            "parental" to "पैरेंटल कंट्रोल",
            "settings" to "सेटिंग्स",
            "add_playlist" to "प्लेलिस्ट जोड़ें",
            "m3u_tab" to "M3U लिंक",
            "xtream_tab" to "Xtream कोड्स",
            "playlist_name" to "प्लेलिस्ट का नाम",
            "server_url" to "सर्वर URL",
            "username" to "यूज़रनेम",
            "password" to "पासवर्ड",
            "m3u_url" to "M3U प्लेलिस्ट लिंक",
            "load_demo" to "मुफ़्त डेमो प्रदाता लोड करें",
            "demo_desc" to "तुरंत उच्च प्रदर्शन वाले सार्वजनिक चैनल और ओपन-सोर्स फिल्में चलाएं।",
            "connect" to "कनेक्ट करें",
            "authenticating" to "सत्यापित किया जा रहा है...",
            "no_playlists" to "कोई प्लेलिस्ट नहीं मिली",
            "no_playlists_desc" to "कृप्या डेमो प्रदाता स्थापित करें या अपनी खुद की सदस्यता विवरण प्रविष्ट करें।",
            "search_hint" to "चैनल या फ़िल्म खोजें...",
            "current_show" to "वर्तमान टीवी प्रोग्राम गाइड",
            "no_epg" to "कोई प्रोग्राम गाइड उपलब्ध नहीं है",
            "player_core" to "प्लेयर इंजन",
            "parental_desc" to "संवेदनशील श्रेणियों या एडल्ट चैनलों को पासवर्ड लॉक करें।",
            "enter_pin" to "पैरेंटल पिन दर्ज करें",
            "set_pin" to "पैरेंटल पिन सेट करें",
            "pin_incorrect" to "गलत पिन! सुरक्षा निषेध।",
            "pin_set_success" to "पैरेंटल पिन सफलतापूर्वक सेट हो गया है।",
            "lock_activated" to "सुरक्षा लॉक सक्रिय किया गया।",
            "lock_disabled" to "सुरक्षा लॉक बंद किया गया।",
            "save_changes" to "बदलाव सहेजें",
            "epg_timeline" to "टीवी प्रोग्राम समय सारिणी (EPG)",
            "play_hd" to "HD डायनामिक प्लेबैक (ऑटो)",
            "switch_core" to "सक्रिय वीडियो इंजन",
            "active_playlist" to "सक्रिय प्रदाता",
            "change_lang" to "ऐप की भाषा बदलें",
            "favorites_empty" to "अभी तक कोई पसंदीदा स्टोर नहीं किया गया।"
        )
    )

    fun getString(langCode: String, key: String): String {
        val bundle = translations[langCode] ?: translations["en"]!!
        return bundle[key] ?: key
    }
}
